### ISSUE TITLE
topic prefix in Recent topics ?

### ISSUE THREAD

**Issue by avandenberghe** [stathis/phpbb31-topicprefixes#1]
hi, 
could topic prefixes be used in the recent topics extension ? i've been trying to do this for a while now.

**Comment by stathis** [comment]
Hello, custom code would be needed in the recent topics extension to read the "topic_prefix" column of the topic row.

**Comment by avandenberghe** [comment]
works now https://github.com/Sajaki/RecentTopics/commit/404d171a19110b7f295ab7506ae15ec6dae4b9d5
