### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by eunaumtenhoid** [stathis/phpbb31-topicprefixes#3]
Error used on aplicationform, contactadmin, ext KB ... 

SQL ERROR [ mysqli ]

Column 'topic_prefix' cannot be null [1048]

**Comment by stathis** [comment]
Can you please supply me with more information?

Thanks

**Comment by eunaumtenhoid** [comment]
look
when using applicationform extension contactadmin and knowlege base in time to send a form in some of these extensions came up this error, you know?

**Comment by stathis** [comment]
Please confirm if this is still an issue.
