### ISSUE TITLE
Phpbb 3.2

### ISSUE THREAD

**Issue by ndmccain** [stathis/phpbb31-topicprefixes#8]
I assume this doesn’t work for PhpBB 3.2 since I have no option to add prefixes.

**Comment by stathis** [comment]
Hello. It actually does work since I'm running it on 3.2.2, but coming from an upgrade. I will check this out on a fresh install.

**Comment by ndmccain** [comment]
That would be wonderful. I was excited when I found it since PhPBB prefix extensions are few and far between.

**Comment by ndmccain** [comment]
I was looking in the wrong place. It’s working!
